lyft/confidant

- Dockerfile
- confidant/ciphermanager.py
If we don't use base64 when USE_ENCRYPTION is set to False, we get control character issues when json.loads is used. We had chosen to not base64 encode the data to make it very obvious in the database that encryption wasn't used, so in this change we're doing a base64, but we're prepending it with UNENCRYPTED_, so that if you look directly at the contents it's clear it's insecure.
> base64 encode and decode content when disabling USE_ENCRYPTION

- .travis.yml
- Makefile
- docs/source/communication/security_reporting.html.markdown
- docs/source/communication/support.html.markdown
- requirements.txt
- setup.cfg
Seems the Ubuntu docker image contains requests, which hid a missing requirement from us. This change adds in the missing requirement and also adds in some missing docs and a basic travis.yml file.
> Add missing requirements, docs, and travis file

- confidant/__init__.py
- confidant/authnz.py
- confidant/ciphermanager.py
- confidant/graphite.py
- confidant/keymanager.py
- confidant/models/__init__.py
- confidant/models/credential.py
- confidant/models/service.py
- confidant/routes/static_files.py
- confidant/routes/v1.py
- scripts/utils.py
This change switching from using a logging object to using logging directly. This fixes the logging issues in docker. This change also reorders the imports to match pep8 style.
> Use logging directly and reorder imports for pep8

- docs/helpers/guide_helpers.rb
The documentation homepage title is currently "Confidant: translation missing: en.index.sub_title" because it is referencing a missing key `index.sub_title`. I changed it to use `index.headline`.
@ryan-lane
> Fix index title by correctly referencing index.headline

- docs/source/basics/install.html.markdown
You'll need to install virtualenv in order to run virtualenv in the
subsequent lines.
> Add python-virtualenv to apt-get docs.

- confidant/models/credential.py
- confidant/models/service.py
- confidant/settings.py
Seems PynamoDB doesn't use AWS_DEFAULT_REGION, but instead has its own method of accessing tables by region, which is specific to the table creation. Set the region explicitly via AWS_DEFAULT_REGION.
> Define table region explicitly

- confidant/authnz/__init__.py
- confidant/authnz/userauth.py
There are a few bugs from changes in the 1.1 branch fixed here:
- Define is_expired() method for NullUserAuthenticator objects, which don't inherit from AbstractUserAuthenticator.
- Fix require_csrf_token() decorator so it calls the wrapped function when USE_AUTH is false.
- Fix infinite SAML login loop that comes from dumb code in /v1/saml/consume that has a list of URLs that are known to be infinite loops.
https://github.com/lyft/confidant/commit/ab8bc60cdbc819e4c43b7a9b7f1a18ee0d43b321
> Fix some bugs with NullUserAuthenticator and reworked login URLs

- confidant/authnz/__init__.py
- confidant/authnz/userauth.py
- confidant/settings.py
- tests/integration/confidant/authnz/authnz_test.py
- tests/unit/confidant/authnz/authnz_test.py
This commit adds a user authenticator that reads authentication from
request headers.  This is useful in the case that you have a load
balancer or other reverse proxy that performs authentication, and simply
being able to make a request to Confidant means that the user is
authenticated.
> Add a user authenticator that uses request headers

- confidant/authnz/userauth.py
- confidant/public/modules/app.js
- confidant/routes/v1.py
- confidant/settings.py
- docs/source/basics/configuration.html.markdown
- tests/integration/confidant/authnz/authnz_test.py
This change makes it possible to modify the xsrf cookie name used by the web frontend. This can be used if the cookie name conflicts with another application in the same domain.
> Make xsrf cookie name configurable

- confidant/routes/v1.py
- confidant/settings.py
We have a use case where we need to be able to save credentials that have the same key names, and use them in the one service.
Since the credential itself acts like a kind of namespace, this looks safe to do, and as we're making the default match the current behaviour, only people who want this feature will get it.
To elaborate on the use case, we use the Service to map into a kubernetes namespace, and the Credentials inside this service with names like `kube-cluster-<clustername>` to contain the cluster details to connect to. Those key/value pairs will be the same (i.e `username`/`password`), so we need to turn off the conflict check.
> Toggle credential conflict check

- confidant/models/__init__.py
- confidant/scripts/bootstrap.py
- confidant/scripts/manage.py
- confidant/scripts/utils.py
- confidant/utils/dynamodb.py
In some cases (like running tests) we don't want to automatically create tables, but instead create them intentionally at a later time with a manage script.
> Add manage script to create dynamo tables

- CHANGELOG.md
- confidant/public/modules/resources/views/credential-details.html
- setup.py
Seems by default for text areas that angularjs trims whitespace. This sets ng-trim to false for credential values. Fixes #156.
>  Fix issue with angular trimming whitespace

- CHANGELOG.md
- confidant/authnz/userauth.py
- setup.py
Currently, once confidant loads and the users file is read once, it's cached for the lifetime of the process. It's possible the user data could be runtime data, so it's better to load it every time. This will make the UI slightly slower. I've added a TODO to cache this and to always check the mtime of the file to see if the cache needs to be refreshed.
> Always read users file, rather than caching in-memory forever

- Dockerfile
* Update `MAINTAINER` to `LABEL maintainer=`
* Bump node version to 8 LTS
* install ca-certificates so curl call doesn't fail because of cert validation
* add `--fail` option to curl so it exits non-0 if something does fail
* add `DEBIAN_FRONTEND=noninteractive` and `--no-install-recommends` to other
`apt-get` call
I also adjusted some of the formatting to be a little more consistent, and added spaces in the `CMD` array (I think this looks nicer, but could take it out).
I didn't add it here, but might also be interesting to add some of the labels from http://label-schema.org/
> Minor Dockerfile updates

- confidant/models/service.py
- confidant/public/modules/common/constants.js
- confidant/public/modules/history/controllers/BlindCredentialHistoryCtrl.js
- confidant/public/modules/history/controllers/CredentialHistoryCtrl.js
- confidant/public/modules/history/controllers/ServiceHistoryCtrl.js
- confidant/public/modules/resources/services/confidantservices.js
- confidant/routes/v1.py
- confidant/services/credentialmanager.py
- confidant/services/servicemanager.py
This change is aimed at returning less credential data, when that data is not necessary. Specifically, it's aiming to remove the return of full credential data when services are fetched through the interface, since those interfaces don't need the credential data.
Along with this change is a new method of doing reverts. I'm starting with service, because it's simpler, but future changes will also make this the method for credentials and blind_credentials, which will let us do reverts without needing to see values.
> Use revert endpoint for reverting service and add metadata only fetch

- confidant/routes/v1.py
- confidant/services/iamrolemanager.py
- confidant/settings.py
- confidant/wsgi.py
In AWS accounts with a large number of IAM roles, the `get_iam_roles_list` endpoint is extremely slow, and can timeout. Also, we tend to call this frequently, and it's difficult to cache in the frontend.
This change caches the IAM role list in-process, and refreshes it on a refresh schedule, in the background.
> Cache iam role list using a background gevent thread

- confidant/models/credential.py
- confidant/public/modules/common/constants.js
- confidant/public/modules/history/controllers/CredentialHistoryCtrl.js
- confidant/public/modules/resources/services/credentials.js
- confidant/routes/v1.py
To make it possible to revert in the history view without needing full access to the decrypted credential pairs, this change adds a revert-to-revision endpoint, and updates the history view to use that endpoint.
> Add a credential revert endpoint for credential history

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/views/credential-details.html
This change adds basic support for ACLs in the backend for get_credential. Right now the rights on the credential are assumed based on what's returned. Modify is always set true because of this. Ideally we'll update the backend to return a list of rights, which can provide hints to the frontend.
> Support ACLs for get_credential in the UI

- confidant/models/credential.py
- confidant/public/modules/common/constants.js
- confidant/public/modules/history/controllers/CredentialHistoryCtrl.js
- confidant/public/modules/history/views/credential-history.html
- confidant/public/modules/resources/services/credentials.js
- confidant/public/styles/main.css
- confidant/routes/v1.py
- tests/unit/confidant/models/credential_test.py
This change modifies the behavior and data in the history view for credentials, to remove sensitive information from that view. A new diff_credential endpoint has been added, which will take two revisions for a credential ID, and returns a non-sensitive diff of the two credentials.
The history view for the credential shows a -/+ view of the two credentials, side-by-side. For credential_pairs (the sensitive part), it shows what's been added and removed, by credential_pair key. In the case a credential pair has been modified, it'll show as being removed and added (similar to a git diff).
> Non-sensitive diff support for credential history

- confidant/public/modules/history/controllers/BlindCredentialHistoryCtrl.js
- confidant/public/modules/history/controllers/CredentialHistoryCtrl.js
- confidant/public/modules/history/controllers/ResourceHistoryCtrl.js
- confidant/public/modules/history/controllers/ServiceHistoryCtrl.js
- confidant/public/modules/history/services/archive.js
- confidant/public/modules/history/views/blind-credential-history.html
- confidant/public/modules/history/views/credential-history.html
- confidant/public/modules/history/views/resources.html
- confidant/public/modules/history/views/service-history.html
- confidant/public/modules/resources/services/credentials.js
- confidant/public/modules/routes/history.js
- confidant/public/styles/main.css
- confidant/routes/v1.py
- confidant/settings.py
- confidant/utils/dynamodb.py
- confidant/wsgi.py
This change refactors the history view to support paging, and also to update the history list efficiently when a resource is reverted.
A new setting `HISTORY_PAGE_LIMIT` is added. By default it isn't set, keeping the original behavior of the endpoints, and the UI. Setting a limit will limit the number of results the revision history endpoints will return. They'll also return a next_page attribute along with the results, which can be passed in for the next set of results. This value is also exposed to the UI via the `get_client_config endpoint`, and is accessible in the angular code via `$scope.clientconfig.generated.history_page_limit`.
The history UI no longer shows a combined history with checkboxes to filter in/out credentials, blind_credentials and services, but instead shows a …
> Paging for history view

- confidant/public/modules/app.js
- confidant/public/modules/history/views/blind-credential-history.html
- confidant/public/modules/history/views/credential-history.html
- confidant/public/modules/history/views/resources.html
- confidant/public/modules/history/views/service-history.html
- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/controllers/ResourceCtrl.js
- confidant/public/modules/resources/controllers/ServiceDetailsCtrl.js
- confidant/public/modules/resources/views/blind-credential-details.html
- confidant/public/modules/resources/views/credential-details.html
- confidant/public/modules/resources/views/resources.html
- confidant/public/modules/resources/views/service-details.html
- confidant/public/modules/routes/resources.js
- confidant/public/styles/main.css
This change refactors the resources view to be consistent with the history view for resources. Rather than showing all resources of one type in the same list, there's a toggle view between credentials, blind credentials, and services. I also pulled the create toggle into the same row as the toggles, and away from the filter, which was confusing for folks in the past.
This change also adds links to a resource's history from the details view. It also styles the action callout buttons (create, edit, save, revert) to make them more apparent.
> Refactor resources view to match history view for resource toggling

- confidant/models/credential.py
- confidant/models/service.py
- confidant/public/modules/common/constants.js
- confidant/public/modules/history/controllers/ServiceHistoryCtrl.js
- confidant/public/modules/history/views/credential-history.html
- confidant/public/modules/history/views/service-history.html
- confidant/public/modules/resources/services/confidantservices.js
- confidant/routes/services.py
- tests/unit/confidant/models/credential_test.py
For consistency, this change refactors the controller and view for service diff to match how credentials is handled. This also adds a diff endpoint for services, with its own ACL.
Also, the diff views didn't show who edited the revisions, or when, so I've added modified_by and modified_date to both diffs.
> Refactor diff view for services to match credentials diff

- confidant/routes/services.py
The original `if` statement to check if there are credentials will never execute if a user deletes all credentials from a service.  `data.get('credentials')` will always return false when the service returns an empty list.  I think the original intention was to check that the key exists.
I've removed the if statement all together since `data.get('credentials', [])` will default to an empty list to check anyway.
> Fix mapping credentials

- confidant/schema/auto_build_schema.py
- requirements.in
- requirements.txt
- requirements3.txt
This change is in response to https://github.com/lyft/confidant/issues/241. It removes webargs and the `-e git` install of toastedmarshmallow fork to fix the build+dist in CI, so we can publish releases.
> Remove webargs and FlaskParser for now

- confidant/schema/credentials.py
- confidant/schema/services.py
Responses call dump, and never load, so we need to use pre_dump, rather than post_load for munging data in the responses before they're sent.
> Use pre_dump, rather than post_load for responses

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
With the recent marshmallow changes, we will always return `credential.credential_pairs`  even if there are no values.
In javascript, `if ({}) { ... }` and `if([]) {...}` will always evaluate to `true`.  This small hotfix will check that there are dictionary keys or length > 0 in an array instead.
The prior changes that affected this:
Setting the key only if the acl module check passes:
https://github.com/lyft/confidant/commit/7f18aedfbed3523aa0d4a4de3d8c93f83be7604e#diff-4f80e4527a99290e72983a3a8cde9808L101
The default value of the marshmallow response object:
https://github.com/lyft/confidant/commit/7f18aedfbed3523aa0d4a4de3d8c93f83be7604e#diff-e6fef3dba80952520b0fe3e8011f5b90R20
> Check that credential keys are empty in if statement

- setup.cfg
- tests/unit/confidant/authnz/authnz_test.py
This change adds full coverage for `confidant/authnz/__init__.py`
> Add unit test coverage for authnz init module

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/views/credential-details.html
- confidant/public/modules/resources/views/service-details.html
- confidant/routes/credentials.py
- confidant/routes/identity.py
- confidant/routes/services.py
- confidant/schema/credentials.py
- confidant/schema/services.py
This change adds permissions hints for the UI, so that we can change the UI behavior based on the permissions available to the end-user.
> Add permission hints to responses and update UI to use them

- confidant/routes/services.py
- tests/unit/confidant/services/credentialmanager_test.py
- Check that a user is able to create a service before calling the rbac check to determine if they're able to map credentials
- Small wording changes on mapping credential deny
- additional unit testing in credential manager
> Separate create service rbac check into its own call

- confidant/public/modules/app.js
- confidant/public/modules/history/controllers/ResourceHistoryCtrl.js
- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/controllers/ResourceCtrl.js
- confidant/public/modules/resources/controllers/ServiceDetailsCtrl.js
- confidant/public/modules/resources/views/credential-details.html
- confidant/public/modules/resources/views/resources.html
This change sets the global permissions in the controllers, uses them in the views, and also ensure the clientconfig loads prior to any modules being loaded.
> Update permissions, global permissions, and fix clientconfig race condition

- confidant/routes/credentials.py
Bug in `update_credential` API endpoint.  Currently after an update of an existing credential, we return the incorrect object thus users will see no credential pairs (see screenshot).
Solution: Return the credentials instead of just permissions after an update.
> Fix update credential not returning credential_response

- confidant/models/credential.py
- setup.cfg
- tests/unit/confidant/routes/credentials_test.py
This adds coverage for lift, get and diff credential routes. It also slightly refactors `Credential.decrypted_credential_pairs` so that it's easier to mock, to avoid KMS calls.
> Coverage for list, get, and diff credential

- confidant/app.py
- requirements.in
- requirements.txt
- requirements3.txt
This PR addressing the following issues:
- `flask.ext.session` -> `flask_session` fixes `ImportError: No module named 'flask.ext'` as the old format `flask.ext.*` is deprecated, see: https://github.com/pallets/flask/issues/1135#issuecomment-61860862
- Version bump from `0.2.1` to `0.2.3` address number of issues with Python 3, see changeset: https://github.com/fengsp/flask-session/blob/master/CHANGES#L31:L37. Here is also a stacktrace I've encountered when I was running `confidant` with `flask-session 0.2.1` with Python 3.7 and Redis as a session storage. 
```
[2020-02-07 23:06:02.669077] ERROR:confidant.app:Exception on /v1/services [GET]
[2020-02-07 23:06:02.669105] Traceback (most recent call last):
[2020-02-07 23:06:02.669214]   File …
```
> Python3 compatibility fixes for flask-session

- .github/workflows/pull_request.yml
- requirements.in
- requirements.txt
- requirements3.txt
During the rollout of `confidant 5.2.0` we ran into a number of issues with Python 3.7.
First of all `pypi` does not have python3.7 binaries for `gevent 1.2.1`: https://pypi.org/project/gevent/1.2.1/#files and same for `greenlet 0.4.12`: https://pypi.org/project/greenlet/0.4.12/#files
I tried bumping `gevent` to `1.3.0` and `greenlet` to `0.4.14`, but `gevent` workers were segfaulting after the startup with the following log statements:
```
[18839] [CRITICAL] WORKER TIMEOUT (pid:20879)
```
After enabling https://docs.python.org/3/library/faulthandler.html we were able to get the actual stacktrace:
```
[2020-02-05 00:17:00.379340] Fatal Python error: Segmentation fault
[2020-02-05 00:17:00.379513] 
[2020-02-05 00:17:00.379578] Thread 0x00007fd427e5c700 (most recent call first):
[2020-02-05 …
```
> Bump gevent and greenlet dependencies for Python 3.7 compatibility

- requirements.in
- requirements.txt
- requirements3.txt
Google has deprecated their google+ signin APIs, which is what their oauth login used to be based on. They have a new oauth flow, which uses the google sign-in apis. Authomatic, in 1.0.0 release has updated the google provider to support the new API.
> Bump authomatic version to 1.0.0

- confidant/authnz/__init__.py
- confidant/authnz/rbac.py
- confidant/routes/services.py
- confidant/settings.py
- pytest.ini
- tests/unit/confidant/authnz/authnz_test.py
- tests/unit/confidant/authnz/rbac_test.py
This change removes the special-cased code for controlling authz for services, and moves everything to using ACL checks. I've added a new default ACL function `default_acl`, which replicates the default behavior of service authz, while making it possible to fully apply ACL checks against services or users for all resources.
> Use ACL for both user and service checks

- confidant/lib/cryptolib.py
Python3 fix for SAML auth when using a client key.
> Decode private key when loaded from file as base64

- confidant/routes/credentials.py
- confidant/schema/credentials.py
- confidant/settings.py
- tests/unit/confidant/routes/credentials_test.py
We haven't set the credential tags attribute that we added in https://github.com/lyft/confidant/pull/270.
- We always populate tags upon creation
- When updating a credential, we update the tags only if the `"tags"` field is present in the request
- When reverting a credential, we use the tag of the revert credential.
> Populate a credential's tag attribute

- confidant/models/credential.py
- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/services/credentials.js
- confidant/public/modules/resources/views/credential-details.html
- confidant/routes/credentials.py
- docker-compose.yml
This change improves the auditing and last-viewed behavior of confidant by only fetching decrypted credential pairs when necessary for the UI. If the end-user loads a credential, it loads `metadata_only=True` by default, and if they unmask the credentials, or edit the credential, it'll fetch the credential with `metadata_only=False`, fetching the credential pairs, and replacing them in-place in the view. The view will keep them loaded while in the same credential view, and will not re-fetch the credential for unmask/edit, as long as the user doesn't leave and re-visit the page.
> Only load credential pairs in UI if user asks to unmask or edits

- confidant/encrypted_settings.py
- confidant/lib/cryptolib.py
- confidant/routes/credentials.py
- confidant/scripts/bootstrap.py
- confidant/scripts/utils.py
- confidant/settings.py
- docker-compose.yml
- tests/unit/confidant/encrypted_settings_test.py
Fixes for bytes vs strings issue in bootstrap script. This change also makes some fixes to how the KMS client is created and passed around, for proper testing in the docker-compose environment.
> Python 3 bytes vs string fixes for bootstrap script

- CHANGELOG.md
- Makefile
- docs/root/install.md
- docs/root/upgrade.md
When we switched from middleman to sphinx, we forgot to fix some inter-doc links. This change updates the links to point to the rendered html files as relative links.
> Fix links between documents in the docs

- confidant/encrypted_settings.py
- confidant/scripts/bootstrap.py
By changing `dict[key]` to `dict.get('key')`, people no longer need to register the optional parameter when bootstrapping secrets
I was confused whether I needed a JSON or YAML file when bootstrapping so adding a bit of extra documentation there
> Don't force people to register bootstrapped secrets

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/views/credential-details.html
- confidant/routes/identity.py
- tests/unit/confidant/routes/identity_test.py
This change adds tags to the edit and new credential UI. The UI currently only allows selection of server defined tags, and specifically only ones defined by the credential rotation settings. Future iterations should allow more server defined tags, or allow user input that isn't from a server defined list.
> Add tags to the edit/new credential UI

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
```
"a" in ["a", "b", "c"]
false
0 in ["a", "b", "c"]
true
3 in ["a", "b", "c"]
false
"a" in {"a": "z"}
true
["a"].includes("a")
true
```
js is nuts to me.
> Minor bugfix to prevent duplicate tags

- confidant/routes/credentials.py
- confidant/utils/misc.py
- requirements.in
- requirements.txt
- requirements3.txt
- tests/unit/confidant/routes/credentials_test.py
When `ENABLE_SAVE_LAST_DECRYPTION_TIME` is enabled and the eye icon is clicked, confidant returns a 5xx because the `last_rotation_date` field of the response is trying to compare a tz unaware timestamp with a tz aware timestamp.  Essentially what was happening was:
```
c = Credential.get(123)
c.last_rotation_date = datetime.now() # no tzinfo
c.save()   # Pynamo will add tzinfo=UTC to last_rotation_date
...
...
c = Credential.get(123)
c.last_decrypted_date = datetime.now() # no tzinfo
c.save()  # Pynamo will add tzinfo=UTC to last_decrypted_date
c.next_rotation_date # uses the unsaved object (`c`) and compares `last_decrypted_date` (no tzinfo with last_rotation_date, which has the tzinfo because pynamo added it
```
Essentially, had we refetched the object (did another …
> Fix timezone comparison issue

- docker-compose.yml
alternatively, `make up` is incorrect and needs to run npm and grunt to
ensure the javascript/css is available
> mapping .:/srv/confidant seems like debugging leftover

- requirements.in
- requirements.txt
- requirements3.txt
Github actions is failing with a combination of python 3.7.8 and pyyaml 5.1.2.  This PR updates pyyaml to 5.3.1.
https://github.com/actions/virtual-environments/issues/1202
> Bump pyyaml to 5.3.1

- MANIFEST.in
Fixes #311, since setup.py pulls in requirements.in.
> Add requirements.in to MANIFEST.in for pip install

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/views/credential-details.html
- confidant/routes/credentials.py
When grabbing metadata of a credential, also check if the user has permissions to decrypt the credential.
This allows us to appropriately show or hide the lock.
> Bug fix in logic that allows checking if a user is allowed to decrypt a credential

- confidant/public/modules/resources/views/credential-details.html
Users were being incorrectly shown decrypt icon on credentials where they had the ability to `create` credentials but didn't have `get` (decrypt) permissions.  
This change shows the option to decrypt credentials only if they have  decrypt permissions
> Don't show decrypt icon if user does not have get permissions

- confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
- confidant/public/modules/resources/views/credential-details.html
https://jira.lyft.net/browse/SECHELP-13408
Previous logic is restricting too much or too little - either everyone who can create sees the div, or people cannot see div when creating. Now change the logic so that it shows up in GET, or CREATE if you can create.
> [SECHELP-13408] Bug fix for show/hide credentials pairs div

- confidant/routes/services.py
This reverts commit 2a24616635f7b0cba949f2c4a7f0fadb75a906d1.
The previous commit had a link to Lyft internal documentation.
> Revert "link to infradocs (#338)"

- confidant/services/jwkmanager.py
Allows us to obtain metrics on `get_jwt`  function so we graph latency on jwt encoding, jwt cache hits and misses.
> Add stats to jwtkmanager

- confidant/routes/jwks.py
- confidant/services/jwkmanager.py
- confidant/settings.py
- requirements.in
- requirements.txt
- tests/conftest.py
- tests/unit/confidant/services/jwkmanager_test.py
- Supports new format for CERTIFICATE_AUTHORITIES where `name` is environment (and multiple keys can be added):
```
[
{
'key': redacted,
'crt': redacted,
'name': 'staging',
'passphrase': redacted, 
'kid': 'staging_slot_a'
}, ...
]
```
- Signing key must be activated for each environment as `ACTIVE_SIGNING_KEYS={"staging": "some_kid", "production": "some_kid"}`, otherwise endpoint will return 400. This will be the key used to sign tokens.
- Public JWKS will expose all keys per environment.
> Support multiple keys per environment

- confidant/routes/services.py
- tests/unit/confidant/routes/services_test.py
Adding pagination for credentials, keeping `limit` and `page` as optional so it's backward compatible (not specifying will keep previous behavior).
> Adding pagination for services

- confidant/routes/jwks.py
- confidant/services/jwkmanager.py
- tests/conftest.py
- tests/unit/confidant/routes/jwks_test.py
We need two parameters in the JWT RBAC check: the logged in user AND the requested JWT id.
Minor variable naming changes.
> Add kwargs to JWT fetch

- confidant/routes/jwks.py
Allow RBAC decisions based on environment.  
Example: Prevents staging from minting prod tokens and vice versa.
> Pass in environment to jwt kwargs

- docs/requirements.txt
`MarkupSafe` is already pulled in from `../requirements.txt` so no need to explicitly include in `docs/requirements.txt`
> Remove duplicate markupsafe from docs/requirements.txt

- confidant/services/jwkmanager.py
- confidant/settings.py
- tests/unit/confidant/services/jwkmanager_test.py
- Refactor settings that relate to our JWT PKI with `JWT_`, which makes it easier to know which configurations affect the PKI.
- Add `JWT_IS_CA_ENCRYPTED` setting that allows us to create an unencrypted base64 encoded `JWT_CERTIFICATE_AUTHORITIES` which is useful for local development
> Prefix JWT settings with JWT_ , add JWT_IS_CA_ENCRYPTED setting

- docs/build.sh
Edit the` build.sh` file for the `build docs` action by editing the required requirements file from `requirements.txt` to `requirements3.txt`.
Example of a failing action:
https://github.com/lyft/confidant/actions/runs/5871680344/job/15921642261
> Fix Build Docs Action

- docs/requirements3.txt
Pin the mistune dependency in the `docs/requirements3.txt` file to fix the doc build action.
Pinning to the 2.0.0 version per the following github [issue](https://github.com/Azure/azure-sdk-for-python/issues/22019#issuecomment-987195928)
> Pin mistune dependency in docs/requirements3.txt

- confidant/services/iamrolemanager.py
- confidant/settings.py
- Allow jitter to be configurable
- Don't wait on background process to populate cache.  Instead, if on first fetch it's empty, populate.
> Improve IAM Role cache

- requirements3.txt
kmsauth v0.6.2 does not exist in artifactory. Reverting confidant to previous reference behavior of pulling latest, rather than pinning to specific version.
> Unpin kmsauth from v0.6.2 which was pulled due to problems

- confidant/routes/blind_credentials.py
- confidant/routes/credentials.py
- confidant/routes/services.py
Sanitize User Input for Services and Credentials 
Also use latest pynamodb notation for querying based on a condition.
> Sanitize User Input for Services and Credentials

- docs/root/install.md
Change install docs to point to Github Container Registry instead of Dockerhub
> fix install docs

- confidant/routes/credentials.py
- confidant/routes/services.py
Was wondering what caused frontend to be so slow? did an analysis on UI and ranked captured network calls by timer. The slow and popular APIs are get and list services/credentials. Emitting stats to understand how slow it is and follow up on action items
> add timer to key GET paths

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- confidant/settings.py
- docker-compose.integration.yml
added 3 settings 'CUSTOM_CERTIFICATE_AUTHORITIES', 'CUSTOM_CA_ENCRYPTED', 'CUSTOM_CA_ACTIVE_KEYS'.
also had to upgrade python minor version because of CI failure
> Add custom CA settings

- confidant/authnz/rbac.py
- tests/unit/confidant/authnz/rbac_test.py
Previous rbac for get certificate:
* CN, and all DNS in SAN needs to match a single regex, and the outcome of 'service_name' needs to be matched to the kms auth identity.
Problem: this limits a lot of the freedom of how DNS in SAN can be defined, especially when 'service_name' does not need to be existent in SAN DNS, even just missing in one of the entries.
Change: loosen the rbac of get cert to just match against CN. For DNS list in SAN, we will skip checking against kms auth identity.
> loosen rbac for get cert - avoid checking every DNS in SAN
