requirements.txt

Upgrade PynamoDB to the latest version, which includes a few bug fixes and such.
https://github.com/jlafon/PynamoDB/blob/1.5.1/docs/release_notes.rst

Upgrade PynamoDB to v1.5.1

---

confidant/routes/v1.py
confidant/settings.py
confidant/webhook.py

Add the ability to notify of credential/service changes via a simple webhook.
Basically a copy and modify of the graphite event notification.

Add a simple webhook

---

confidant/settings.py
docs/source/basics/configuration.html.markdown

Partially addresses #113. @ryan-lane

Added saml documentation

---

README.md
piptools_requirements.in
piptools_requirements.txt
requirements.in
requirements.txt

Fix: see https://github.com/pyca/cryptography/issues/3834#issuecomment-326296103

Fix travis tests

---

confidant/public/modules/resources/controllers/ServiceDetailsCtrl.js
confidant/public/modules/resources/views/service-details.html

This checks that if the user is creating a new service, they do not override an existing service.

Added check to prevent creating a service that already exists

---

confidant/public/index.html

Add title to index.html page

---

CHANGELOG.md
requirements.in
requirements.txt
setup.py

One part of a series of commits and releases for upgrading PynamoDB to a modern release.

Upgrade pynamo to 1.5.4 and bump version

---

piptools_requirements.in
piptools_requirements.txt
requirements.in
requirements.txt

This update fixes vulnerability https://www.sourceclear.com/vulnerability-database/libraries/pyasn1/python/pypi/lid-200413

Upgrade pyasn1 to 0.4.4

---

confidant/ciphermanager.py

Fix USE_ENCRYPTION=false in python3

---

.gitignore
confidant/models/blind_credential.py
confidant/public/modules/common/constants.js
confidant/public/modules/history/controllers/BlindCredentialHistoryCtrl.js
confidant/public/modules/resources/services/blindcredentials.js
confidant/routes/v1.py

This change adds an endpoint for reverting blind credentials to a specific revision, and updates the frontend code related to this as well.

Revert to revision for blind credentials

---

confidant/routes/v1.py

- Check that user has access to credential metadata
- If user has access to metadata, check that they have access to the credential pairs.

Check that user has access to metadata and credentialpair

---

confidant/routes/credentials.py
confidant/routes/services.py

This change extends the acl checks into other functions that return resource data.

Add acl checks for the rest of the resource endpoints in credentials and services

---

requirements.in
requirements.txt
requirements3.txt

Newest version of kmsauth will use a more efficient LRU, if it's installed, so upgrade kmsauth and include lru-dict.

Upgrade kmsauth and use lru-dict

---

confidant/authnz/__init__.py

Small tidying: remove unreachable code

---

confidant/schema/credentials.py
tests/unit/confidant/routes/credentials_test.py

We want the client to have this information as well so we can populate the UI

Send back last rotated date to client

---

confidant/public/modules/resources/controllers/CredentialDetailsCtrl.js
confidant/public/modules/resources/views/credential-details.html
confidant/schema/credentials.py

Add info in the credential UI for the next required rotation date for a credential.

Show next rotation time in credential UI

---

README.md

Add our logo

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
.pre-commit-config.yaml
confidant/authnz/userauth.py
confidant/models/credential.py
docker-compose.integration.yml
requirements.in
requirements.txt
salt/modules/grains/parse_env.py
tests/conftest.py

- py36 is EOL
- Upgrade pre-commit dependencies
- Require pyjwt to minimum 2.6.0 which should include jwt header fixes.

Remove py36.  Require minimum pyjwt 2.6.0

---

confidant/routes/jwks.py
confidant/services/jwkmanager.py
tests/unit/confidant/services/jwkmanager_test.py

Adding cache for private keys and removing unused code

Add private key cache and remove unused code

---

confidant/routes/credentials.py
tests/unit/confidant/routes/credentials_test.py

Adding pagination for credentials, keeping `limit` and `page` as optional so it's backward compatible (not specifying will keep previous behavior).

Adding pagination for credentials

---

confidant/routes/credentials.py
confidant/scripts/archive.py
confidant/services/credentialmanager.py
tests/unit/confidant/scripts/archive_test.py

- Moving archive functions to service
- Implementing route for FE

Implement archive route

---

confidant/services/jwkmanager.py

Also minor refactor to prepend all jwt ca related stats with `jwt`.

Add stats for signing key used

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
confidant/routes/services.py
requirements.in
requirements.txt

Ingress sometimes is being affected by 4xx's, this will add more observability for when this issue happens.

Add logging to confidant ingress

---

docs/requirements3.txt

Followup for #396 
Continue fixing the build docs action by editing all the `requirements.txt` to `requirements3.txt`

Update and rename docs/requirements.txt to docs/requirements3.txt

---

confidant/authnz/__init__.py
requirements.in
requirements3.txt

Followup to https://github.com/lyft/python-kmsauth/pull/18
Start using the new performance parameters in kmsauth

use kmsauth performance parameters

---

requirements3.txt

Pinning to v0.6.3 per ramon petgrave

Pin kmsauth to v0.6.3

---

confidant/routes/services.py

Follow up to https://github.com/lyft/confidant/pull/431, add more detailed timers breakdown to see which one is the worst contributors

Add more timers to get service by id

---

README.md

[SECFOUND-3926](https://jira.lyft.net/browse/SECFOUND-3926)

[SECFOUND-3926] Add Archiving Notice in README.md
